name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          usedocker: true
      - name: Update database
        run: |
                heroku run dotnet tool install --global dotnet-ef
                heroku run dotnet tool restore
                heroku run dotnet-ef database update
        env:
            ASPNETCORE_ENVIRONMENT: Production
            
      
       
     
